# Site settings
title: Ethereal
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: This is <strong>Ethereal</strong>, a free site template by AJ for <a href="https://html5up.net">HTML5 UP</a>. Itâ€™s fully responsive, built on HTML5 and CSS3, and released entirely for free under the Creative Commons license. Hope you dig it :)
baseurl: "/ethereal-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://lesliemor.github.io/" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/leslie-moreno/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
